### ISSUE TITLE
крешь, плачу 500 славы

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1017]
show zones 12500
630H 179M ??? Зауч:0 ОЗ:0 34L 0G Вых:СВЮv> show zones 12500
[Переподключение(1)...
![image](https://user-images.githubusercontent.com/42086238/129028651-73d40843-f616-4520-b72e-0fe022f144e3.png)
тута

**Comment by bylins** [comment]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7621859 in __GI_abort () at abort.c:79
#2  0x00007ffff7a0a109 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000555556623b36 in std::__debug::vector<ZoneData, std::allocator<ZoneData> >::operator[] (this=0x555558d0c7b8 <(anonymous namespace)::global_objects()::storage+3224>, __n=568)
    at /usr/include/c++/10/debug/vector:427
#4  0x0000555557404add in do_show (ch=0x621001d9fd00, argument=0x7fffffffe0f5 "zones 12500") at /home/stribog/mud/src/act_wizard.cpp:3419
#5  0x0000555556c6645f in command_interpreter (ch=0x621001d9fd00, argument=0x7fffffffe0f0 "show zones 12500") at /home/stribog/mud/src/interpreter.cpp:1310
#6  0x0000555556620bef in process_io (epoll=13, mother_desc=11, events=0x62700055c100) at /home/stribog/mud/src/comm.cpp:1282
#7  0x000055555660697b in game_loop (epoll=13, mother_desc=11) at /home/stribog/mud/src/comm.cpp:1490
#8  0x0000555556604dae in stop_game (port=5555) at /home/stribog/mud/src/comm.cpp:816
#9  0x00005555566047f7 in main_function (argc=2, argv=0x7fffffffeb38) at /home/stribog/mud/src/comm.cpp:757
#10 0x0000555556603472 in main (argc=2, argv=0x7fffffffeb38) at /home/stribog/mud/src/main.cpp:4
