### ISSUE TITLE
Не тикать в тестовых зонах на земле антуражным шмоткам таймер

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1037]
Так как таймер выставляется 30 то не стоит тикать

**Comment by bylins** [comment]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7621859 in __GI_abort () at abort.c:79
#2  0x00007ffff7a0a109 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000555556624b36 in std::__debug::vector<ZoneData, std::allocator<ZoneData> >::operator[] (this=0x555558d10c78 <(anonymous namespace)::global_objects()::storage+3224>, __n=17692)
    at /usr/include/c++/10/debug/vector:427
#4  0x0000555556a1fcf7 in NO_TIMER (obj=0x61b00509e390) at /home/stribog/mud/src/game_limits.cpp:1044
#5  0x0000555556a19116 in operator() (__closure=0x7fffffffdb10, j=std::shared_ptr<class OBJ_DATA> (use count 5, weak count 0) = {...}) at /home/stribog/mud/src/game_limits.cpp:1416
#6  0x0000555556a1f21b in std::__invoke_impl<void, obj_point_update()::<lambda(const shared_ptr&)>&, const std::shared_ptr<OBJ_DATA>&>(std::__invoke_other, struct {...} &) (__f=...)
    at /usr/include/c++/10/bits/invoke.h:60
#7  0x0000555556a1e90b in std::__invoke_r<void, obj_point_update()::<lambda(const shared_ptr&)>&, const std::shared_ptr<OBJ_DATA>&>(struct {...} &) (__fn=...)
    at /usr/include/c++/10/bits/invoke.h:110
#8  0x0000555556a1e16e in std::_Function_handler<void(const std::shared_ptr<OBJ_DATA>&), obj_point_update()::<lambda(const shared_ptr&)> >::_M_invoke(const std::_Any_data &, const std::shared_ptr<OBJ_DATA> &) (__functor=..., __args#0=std::shared_ptr<class OBJ_DATA> (use count 5, weak count 0) = {...}) at /usr/include/c++/10/bits/std_function.h:291
#9  0x00005555572edca5 in std::function<void (std::shared_ptr<OBJ_DATA> const&)>::operator()(std::shared_ptr<OBJ_DATA> const&) const (this=0x7fffffffdb10,
    __args#0=std::shared_ptr<class OBJ_DATA> (use count 5, weak count 0) = {...}) at /usr/include/c++/10/bits/std_function.h:622
#10 0x00005555572e875c in std::for_each<__gnu_debug::_Safe_iterator<std::__cxx1998::_List_const_iterator<std::shared_ptr<OBJ_DATA> >, std::__debug::list<std::shared_ptr<OBJ_DATA>, std::allocator<std::shared_ptr<OBJ_DATA> > >, std::bidirectional_iterator_tag>, std::function<void (std::shared_ptr<OBJ_DATA> const&)> >(__gnu_debug::_Safe_iterator<std::__cxx1998::_List_const_iterator<std::shared_ptr<OBJ_DATA> >, std::__debug::list<std::shared_ptr<OBJ_DATA>, std::allocator<std::shared_ptr<OBJ_DATA> > >, std::bidirectional_iterator_tag>, __gnu_debug::_Safe_iterator<std::__cxx1998::_List_const_iterator<std::shared_ptr<OBJ_DATA> >, std::__debug::list<std::shared_ptr<OBJ_DATA>, std::allocator<std::shared_ptr<OBJ_DATA> > >, std::bidirectional_iterator_tag>, std::function<void (std::shared_ptr<OBJ_DATA> const&)>) (Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
__first=, Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
__last=, __f=...) at /usr/include/c++/10/bits/stl_algo.h:3844
#11 0x00005555572dfbf5 in WorldObjects::foreach_on_copy(std::function<void (std::shared_ptr<OBJ_DATA> const&)> const&) const (
    this=0x555558d10388 <(anonymous namespace)::global_objects()::storage+936>, function=...) at /home/stribog/mud/src/world_objects.cpp:191
#12 0x0000555556a1a8cd in obj_point_update () at /home/stribog/mud/src/game_limits.cpp:1310
#13 0x0000555556b13911 in std::__invoke_impl<void, void (*&)()> (__f=@0x606000001298: 0x555556a1a7cb <obj_point_update()>) at /usr/include/c++/10/bits/invoke.h:60
#14 0x0000555556b1336b in std::__invoke_r<void, void (*&)()> (__fn=@0x606000001298: 0x555556a1a7cb <obj_point_update()>) at /usr/include/c++/10/bits/invoke.h:110
#15 0x0000555556b12c2a in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/10/bits/std_function.h:291
#16 0x0000555556aef336 in std::function<void ()>::operator()() const (this=0x606000001298) at /usr/include/c++/10/bits/std_function.h:622
#17 0x0000555556acb05a in (anonymous namespace)::SimpleCall::perform (this=0x606000001290) at /home/stribog/mud/src/heartbeat.cpp:121
#18 0x0000555556ad6a99 in Heartbeat::pulse (this=0x555558d109a0 <(anonymous namespace)::global_objects()::storage+2496>, missed_pulses=2, Python Exception <class 'gdb.error'> No type named std::__detail::_Hash_node<struct std::pair<unsigned long const, double>, false>.:
label=std::__debug::unordered_map with 3 elements)
    at /home/stribog/mud/src/heartbeat.cpp:634
#19 0x0000555556ad5ca4 in Heartbeat::operator() (this=0x555558d109a0 <(anonymous namespace)::global_objects()::storage+2496>, missed_pulses=2) at /home/stribog/mud/src/heartbeat.cpp:583
#20 0x0000555556607993 in game_loop (epoll=13, mother_desc=11) at /home/stribog/mud/src/comm.cpp:1494
#21 0x0000555556605dae in stop_game (port=5555) at /home/stribog/mud/src/comm.cpp:816
#22 0x00005555566057f7 in main_function (argc=2, argv=0x7fffffffeb38) at /home/stribog/mud/src/comm.cpp:757
#23 0x0000555556604472 in main (argc=2, argv=0x7fffffffeb38) at /home/stribog/mud/src/main.cpp:4
(gdb) quit

**Comment by bylins** [comment]
исправлено но неработает

**Comment by bylins** [comment]
сделано
