### ISSUE TITLE
Новй крешь

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1055]
Program terminated with signal SIGSEGV, Segmentation fault.
#0  FLAG_DATA::get<unsigned int> (this=0x7b4, packed_flag=8) at /home/mud/mud/src/structs.h:1292
1292            return 0 != (m_flags[packed_flag >> 30] & (packed_flag & 0x3fffffff));
[Current thread is 1 (Thread 0x7f8403faa980 (LWP 701282))]
(gdb) bt
#0  FLAG_DATA::get<unsigned int> (this=0x7b4, packed_flag=8) at /home/mud/mud/src/structs.h:1292
#1  0x000055c55b145e56 in FLAG_DATA::get<int> (this=0x7b4, packed_flag=8) at /home/mud/mud/src/structs.h:1295
#2  0x000055c55b14663f in CHAR_DATA::is_npc (this=0x0) at /home/mud/mud/src/chars/char.h:657
#3  0x000055c55b53b46d in npc_group (ch=0x55c56becdcf0) at /home/mud/mud/src/spec_procs.cpp:2333
#4  0x000055c55b284e8a in operator() (__closure=0x55c56da63de0, ch=std::shared_ptr<CHAR_DATA> (use count 2, weak count 0) = {...}) at /home/mud/mud/src/fightsystem/mobact.cpp:1226
#5  0x000055c55b2868af in std::__invoke_impl<void, mobile_activity(int, int)::<lambda(const shared_ptr&)>&, const std::shared_ptr<CHAR_DATA>&>(std::__invoke_other, struct {...} &) (
    __f=...) at /usr/include/c++/10/bits/invoke.h:60
#6  0x000055c55b2866c8 in std::__invoke_r<void, mobile_activity(int, int)::<lambda(const shared_ptr&)>&, const std::shared_ptr<CHAR_DATA>&>(struct {...} &) (__fn=...)
    at /usr/include/c++/10/bits/invoke.h:110
#7  0x000055c55b286403 in std::_Function_handler<void(const std::shared_ptr<CHAR_DATA>&), mobile_activity(int, int)::<lambda(const shared_ptr&)> >::_M_invoke(const std::_Any_data &, const std::shared_ptr<CHAR_DATA> &) (__functor=..., __args#0=std::shared_ptr<CHAR_DATA> (use count 2, weak count 0) = {...}) at /usr/include/c++/10/bits/std_function.h:291
#8  0x000055c55b6db919 in std::function<void (std::shared_ptr<CHAR_DATA> const&)>::operator()(std::shared_ptr<CHAR_DATA> const&) const (this=0x7ffe3f507e60,
    __args#0=std::shared_ptr<CHAR_DATA> (use count 2, weak count 0) = {...}) at /usr/include/c++/10/bits/std_function.h:622
#9  0x000055c55b6da8af in std::for_each<std::_List_const_iterator<std::shared_ptr<CHAR_DATA> >, std::function<void (std::shared_ptr<CHAR_DATA> const&)> >(std::_List_const_iterator<std::shared_ptr<CHAR_DATA> >, std::_List_const_iterator<std::shared_ptr<CHAR_DATA> >, std::function<void (std::shared_ptr<CHAR_DATA> const&)>) (__first=
  std::shared_ptr<CHAR_DATA> (use count 2, weak count 0) = {get() = 0x55c56becdcf0}, __last=std::shared_ptr<CHAR_DATA> (use count 16281088, weak count 1045425336) = {get() = 0x6045},
    __f=...) at /usr/include/c++/10/bits/stl_algo.h:3844
#10 0x000055c55b6d9482 in Characters::foreach_on_copy(std::function<void (std::shared_ptr<CHAR_DATA> const&)>) const (
    this=0x55c55ba57480 <(anonymous namespace)::global_objects()::storage+1120>, function=...) at /home/mud/mud/src/chars/world.characters.cpp:81
#11 0x000055c55b28592e in mobile_activity (activity_level=568150, missed_pulses=10) at /home/mud/mud/src/fightsystem/mobact.cpp:946
#12 0x000055c55b2d9201 in (anonymous namespace)::MobActCall::perform (this=0x55c55c8f0e50, pulse_number=568150) at /home/mud/mud/src/heartbeat.cpp:129
#13 0x000055c55b2defcf in Heartbeat::pulse (this=0x55c55ba57600 <(anonymous namespace)::global_objects()::storage+1504>, missed_pulses=0, label=std::unordered_map with 2 elements = {...})
    at /home/mud/mud/src/heartbeat.cpp:634
#14 0x000055c55b2dea34 in Heartbeat::operator() (this=0x55c55ba57600 <(anonymous namespace)::global_objects()::storage+1504>, missed_pulses=0) at /home/mud/mud/src/heartbeat.cpp:583
#15 0x000055c55b13a1c4 in game_loop (epoll=13, mother_desc=11) at /home/mud/mud/src/comm.cpp:1494
#16 0x000055c55b139343 in stop_game (port=4000) at /home/mud/mud/src/comm.cpp:816
#17 0x000055c55b139084 in main_function (argc=3, argv=0x7ffe3f5085c8) at /home/mud/mud/src/comm.cpp:757
#18 0x000055c55b13864d in main (argc=3, argv=0x7ffe3f5085c8) at /home/mud/mud/src/main.cpp:4
(gdb)

**Comment by bylins** [comment]
интересно а почему раньше то не крешало?

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/130805916-79827305-710b-49d8-b6be-06ce87f5ca14.png)
а если лидер NULL ?
