### ISSUE TITLE
Крешь

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1153]
Oct 29 22:09:28 :: [MAG DAMAGE] огненный вихрь damage Есгар (26)
Oct 29 22:09:28 :: pk_agro_action: огненный вихрь vs Спитигнев, pkType = 1
Oct 29 22:09:28 :: pk_agro_action: огненный вихрь vs Спитигнев, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] огненный вихрь damage Спитигнев (243)
Oct 29 22:09:28 :: pk_agro_action: черт vs Спитигнев, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage Спитигнев (5)
Oct 29 22:09:28 :: pk_agro_action: черт vs Сантур, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage Сантур (5)
Oct 29 22:09:28 :: pk_agro_action: черт vs Есгар, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage Есгар (5)
Oct 29 22:09:28 :: pk_agro_action: черт vs Алвис, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage Алвис (5)
Oct 29 22:09:28 :: pk_agro_action: черт vs Милий, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage Милий (5)
Oct 29 22:09:28 :: pk_agro_action: черт vs Миролис, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage Миролис (5)
Oct 29 22:09:28 :: pk_agro_action: черт vs Веред, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage Веред (5)
Oct 29 22:09:28 :: pk_agro_action: черт vs Алвис, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage наемный охранник Кристер (5)
Oct 29 22:09:28 :: pk_agro_action: черт vs Честимир, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage Честимир (5)
Oct 29 22:09:28 :: pk_agro_action: черт vs Веред, pkType = 1
Oct 29 22:09:28 :: [MAG DAMAGE] черт damage черный василиск (5)
Oct 29 22:09:28 :: SAVING: Caster==Милий  Mob==черт vnum==92401 Level==37 type==3 base_save==93 stat_bonus==22 awake_bonus==0 save_ext==-78 cast_apply==0 result==-7 new_random==188
Oct 29 22:09:28 :: SAVING: Caster==Спитигнев  Mob==черт vnum==92401 Level==37 type==3 base_save==93 stat_bonus==22 awake_bonus==0 save_ext==-78 cast_apply==0 result==-7 new_random==192
Oct 29 22:09:28 :: pk_agro_action: черт vs Спитигнев, pkType = 1
Oct 29 22:09:28 :: pk_agro_action: черт vs Спитигнев, pkType = 1
Oct 29 22:09:28 :: Crash detected !

**Comment by bylins** [comment]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  std::_List_iterator<std::shared_ptr<AFFECT_DATA<EApplyLocation> > >::operator++ (this=0x7ffd074ede68) at /usr/include/c++/9/bits/stl_list.h:219
219             _M_node = _M_node->_M_next;
[Current thread is 1 (Thread 0x7f438ea8a980 (LWP 398485))]
(gdb) bt
#0  std::_List_iterator<std::shared_ptr<AFFECT_DATA<EApplyLocation> > >::operator++ (this=0x7ffd074ede68) at /usr/include/c++/9/bits/stl_list.h:219
#1  0x00005626a79bacee in battle_affect_update (ch=0x5626bdbecc50) at /home/mud/mud/src/affects/affect_data.cpp:256
#2  0x00005626a75c95c0 in update_round_affs () at /home/mud/mud/src/fightsystem/fight.cpp:1715
#3  0x00005626a75caecf in perform_violence () at /home/mud/mud/src/fightsystem/fight.cpp:2109
#4  0x00005626a765c925 in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/9/bits/std_function.h:300
#5  0x00005626a7653690 in std::function<void ()>::operator()() const (this=0x5626a8198db8) at /usr/include/c++/9/bits/std_function.h:688
#6  0x00005626a7641500 in (anonymous namespace)::SimpleCall::perform (this=0x5626a8198db0) at /home/mud/mud/src/heartbeat.cpp:121
#7  0x00005626a76472f9 in Heartbeat::pulse (this=0x5626a7ddec80 <(anonymous namespace)::global_objects()::storage+1504>, missed_pulses=0, label=std::unordered_map with 3 elements = {...})
    at /home/mud/mud/src/heartbeat.cpp:634
#8  0x00005626a7646d68 in Heartbeat::operator() (this=0x5626a7ddec80 <(anonymous namespace)::global_objects()::storage+1504>, missed_pulses=0) at /home/mud/mud/src/heartbeat.cpp:583
#9  0x00005626a74a4248 in game_loop (epoll=10, mother_desc=8) at /home/mud/mud/src/comm.cpp:1494
#10 0x00005626a74a33bd in stop_game (port=4000) at /home/mud/mud/src/comm.cpp:816
#11 0x00005626a74a30fe in main_function (argc=3, argv=0x7ffd074ee608) at /home/mud/mud/src/comm.cpp:757
#12 0x00005626a74a263d in main (argc=3, argv=0x7ffd074ee608) at /home/mud/mud/src/main.cpp:4

```
