### ISSUE TITLE
КРеш

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1252]
Dec 11 10:37:41 :: [Extract char] Stop function for char дрофа
Dec 11 10:37:41 :: <Тупша, 281347> {11137} [вз все.ингр]
Dec 11 10:37:41 :: <Родаси, 281347> {98266} [ю]
Dec 11 10:37:41 :: <Тупша, 281348> {11137} [восток]
Dec 11 10:37:41 :: <Тупша, 281349> {11139} [вз все.ингр]
Dec 11 10:37:41 :: <Тупша, 281350> {11139} [запад]
Dec 11 10:37:41 :: <Марея, 281350> {14209} [см]
Dec 11 10:37:41 :: <Тупша, 281351> {11137} [вз все.ингр]
Dec 11 10:37:41 :: <Марея, 281351> {14209} [прик все пом]
Dec 11 10:37:41 :: <Тупша, 281352> {11137} [юг]
Dec 11 10:37:41 :: <Риволн, 281352> {37876} [копать]
Dec 11 10:37:41 :: <Марея, 281352> {14209} [прик все пом]
Dec 11 10:37:41 :: Load obj #86155 by измученный пленник (mload)
Dec 11 10:37:41 :: <Тупша, 281353> {11143} [вз все.ингр]
Dec 11 10:37:41 :: <Магиль, 281353> { 4101} [см]
Dec 11 10:37:41 :: <Родаси, 281353> {98262} [ю]
Dec 11 10:37:41 :: <Марея, 281353> {14209} [прик все пом]
Dec 11 10:37:41 :: Crash detected !

**Comment by bylins** [comment]
```
#0  FLAG_DATA::get<unsigned int> (this=0x7c4, packed_flag=8) at /home/mud/mud/src/structs.h:1297
#1  0x0000558ba98ca21a in FLAG_DATA::get<int> (this=0x7c4, packed_flag=8) at /home/mud/mud/src/structs.h:1300
#2  0x0000558ba98caa2b in CHAR_DATA::is_npc (this=0x0) at /home/mud/mud/src/chars/char.h:663
#3  0x0000558ba9a049f0 in raw_kill (ch=0x558bc8696ee0, killer=0x0) at /home/mud/mud/src/fightsystem/fight_stuff.cpp:743
#4  0x0000558ba9a03070 in die (ch=0x558bc8696ee0, killer=0x0) at /home/mud/mud/src/fightsystem/fight_stuff.cpp:408
#5  0x0000558ba99ba353 in do_wdamage (room=0x558bb0fea490, argument=0x7ffc1c3815b7 " \036\062\061\061\060\065\070\067 370") at /home/mud/mud/src/dg_script/dg_wldcmd.cpp:544
#6  0x0000558ba99bbb5d in wld_command_interpreter (room=0x558bb0fea490, argument=0x7ffc1c3815b0 "wdamage \036\062\061\061\060\065\070\067 370")
    at /home/mud/mud/src/dg_script/dg_wldcmd.cpp:942
#7  0x0000558ba999e329 in timed_script_driver (go=0x558bb0fea490, trig=0x558bb0feada0, type=2, mode=1) at /home/mud/mud/src/dg_script/dg_scripts.cpp:5026
#8  0x0000558ba999c896 in script_driver (go=0x558bb0fea490, trig=0x558bb0feada0, type=2, mode=1) at /home/mud/mud/src/dg_script/dg_scripts.cpp:4722
#9  0x0000558ba9986aed in trig_wait_event (info=0x558bc8082550) at /home/mud/mud/src/dg_script/dg_scripts.cpp:782
#10 0x0000558ba9ee2d8c in process_events () at /home/mud/mud/src/dg_script/dg_event.cpp:83
#11 0x0000558ba9a81209 in std::__invoke_impl<void, void (*&)()> (__f=@0x558babbfab98: 0x558ba9ee2ceb <process_events()>) at /usr/include/c++/11/bits/invoke.h:61
#12 0x0000558ba9a81093 in std::__invoke_r<void, void (*&)()> (__fn=@0x558babbfab98: 0x558ba9ee2ceb <process_events()>) at /usr/include/c++/11/bits/invoke.h:111
#13 0x0000558ba9a80cd3 in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/11/bits/std_function.h:291
#14 0x0000558ba9a778c0 in std::function<void ()>::operator()() const (this=0x558babbfab98) at /usr/include/c++/11/bits/std_function.h:560
#15 0x0000558ba9a6504a in (anonymous namespace)::SimpleCall::perform (this=0x558babbfab90) at /home/mud/mud/src/heartbeat.cpp:121
#16 0x0000558ba9a6af2e in Heartbeat::pulse (this=0x558baa2215a0 <(anonymous namespace)::global_objects()::storage+1504>, missed_pulses=1, label=std::unordered_map with 0 elements)
    at /home/mud/mud/src/heartbeat.cpp:634
#17 0x0000558ba9a6a9a0 in Heartbeat::operator() (this=0x558baa2215a0 <(anonymous namespace)::global_objects()::storage+1504>, missed_pulses=1) at /home/mud/mud/src/heartbeat.cpp:583
#18 0x0000558ba98be327 in game_loop (epoll=10, mother_desc=8) at /home/mud/mud/src/comm.cpp:1494
#19 0x0000558ba98bd431 in stop_game (port=4000) at /home/mud/mud/src/comm.cpp:816
#20 0x0000558ba98bd142 in main_function (argc=3, argv=0x7ffc1c3821e8) at /home/mud/mud/src/comm.cpp:757
#21 0x0000558ba98bc6ad in main (argc=3, argv=0x7ffc1c3821e8) at /home/mud/mud/src/main.cpp:4
(gdb)
```

**Comment by bylins** [comment]
испправил
