### ISSUE TITLE
Очередной креш и что-то новое

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1283]
Dec 24 20:34:08 :: DmetrLog. Name(player): Умеля, class: 1, remort:20, level:30, dmg: 528, over_dmg:438
Dec 24 20:34:08 :: Killed: 30 517 0
Dec 24 20:34:08 :: [Extract char] Start function for char беззащитный зайчонок VNUM: 15010
Dec 24 20:34:08 :: [Extract char] Stop function for char беззащитный зайчонок
Dec 24 20:34:08 :: pk_agro_action: Умеля vs прелютый волк, pkType = 1
Dec 24 20:34:08 :: [MAG DAMAGE] Умеля damage прелютый волк (213)
Dec 24 20:34:08 :: SAVING: Caster==Умеля  Mob==прелютый волк vnum==15034 Level==32 type==3 base_save==94 stat_bonus==23 awake_bonus==0 save_ext==0 cast_apply==118 result==189 new_random==12
9
Dec 24 20:34:08 :: DmetrLog. Name(player): Умеля, class: 1, remort:20, level:30, dmg: 759, over_dmg:692
Dec 24 20:34:08 :: Killed: 32 2256 0
Dec 24 20:34:08 :: [Extract char] Start function for char прелютый волк VNUM: 15034
Dec 24 20:34:08 :: [Extract char] Stop function for char прелютый волк
Dec 24 20:34:08 :: SYSERR: affect_remove(Килиан) when no affects...
Dec 24 20:34:08 :: Crash detected !

**Comment by bylins** [comment]
```
#0  std::_List_iterator<std::shared_ptr<AFFECT_DATA<EApplyLocation> > >::operator++ (this=0x7ffce888b948) at /usr/include/c++/11/bits/stl_list.h:219
#1  0x00005615c59cd2db in operator() (__closure=0x7ffce888bab0, i=std::shared_ptr<CHAR_DATA> (use count 3, weak count 0) = {...}) at /home/mud/mud/src/affects/affect_data.cpp:208
#2  0x00005615c59d0fe1 in std::__invoke_impl<void, player_affect_update()::<lambda(const shared_ptr&)>&, const std::shared_ptr<CHAR_DATA>&>(std::__invoke_other, struct {...} &) (__f=...)
    at /usr/include/c++/11/bits/invoke.h:61
#3  0x00005615c59d0d61 in std::__invoke_r<void, player_affect_update()::<lambda(const shared_ptr&)>&, const std::shared_ptr<CHAR_DATA>&>(struct {...} &) (__fn=...)
    at /usr/include/c++/11/bits/invoke.h:111
#4  0x00005615c59d0b33 in std::_Function_handler<void(const std::shared_ptr<CHAR_DATA>&), player_affect_update()::<lambda(const shared_ptr&)> >::_M_invoke(const std::_Any_data &, const std::shared_ptr<CHAR_DATA> &) (__functor=..., __args#0=std::shared_ptr<CHAR_DATA> (use count 3, weak count 0) = {...}) at /usr/include/c++/11/bits/std_function.h:291
#5  0x00005615c5a79355 in std::function<void (std::shared_ptr<CHAR_DATA> const&)>::operator()(std::shared_ptr<CHAR_DATA> const&) const (this=0x7ffce888bab0,
    __args#0=std::shared_ptr<CHAR_DATA> (use count 3, weak count 0) = {...}) at /usr/include/c++/11/bits/std_function.h:560
#6  0x00005615c5a7830e in std::for_each<std::_List_const_iterator<std::shared_ptr<CHAR_DATA> >, std::function<void (std::shared_ptr<CHAR_DATA> const&)> >(std::_List_const_iterator<std::shared_ptr<CHAR_DATA> >, std::_List_const_iterator<std::shared_ptr<CHAR_DATA> >, std::function<void (std::shared_ptr<CHAR_DATA> const&)>) (__first=
  std::shared_ptr<CHAR_DATA> (use count 3, weak count 0) = {get() = 0x5615dc8c6090}, __last=std::shared_ptr<CHAR_DATA> (use count 1210117251, weak count 1223196040) = {get() = 0x6445},
    __f=...) at /usr/include/c++/11/bits/stl_algo.h:3820
#7  0x00005615c5a76ed8 in Characters::foreach_on_copy(std::function<void (std::shared_ptr<CHAR_DATA> const&)>) const (
    this=0x5615c5dff420 <(anonymous namespace)::global_objects()::storage+1120>, function=...) at /home/mud/mud/src/chars/world.characters.cpp:81
#8  0x00005615c59cd652 in player_affect_update () at /home/mud/mud/src/affects/affect_data.cpp:193
#9  0x00005615c565e1bd in std::__invoke_impl<void, void (*&)()> (__f=@0x5615c6bb3f08: 0x5615c59cd614 <player_affect_update()>) at /usr/include/c++/11/bits/invoke.h:61
#10 0x00005615c565e047 in std::__invoke_r<void, void (*&)()> (__fn=@0x5615c6bb3f08: 0x5615c59cd614 <player_affect_update()>) at /usr/include/c++/11/bits/invoke.h:111
#11 0x00005615c565dc87 in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/11/bits/std_function.h:291
#12 0x00005615c5654874 in std::function<void ()>::operator()() const (this=0x5615c6bb3f08) at /usr/include/c++/11/bits/std_function.h:560
#13 0x00005615c5641ffe in (anonymous namespace)::SimpleCall::perform (this=0x5615c6bb3f00) at /home/mud/mud/src/heartbeat.cpp:121
#14 0x00005615c5647ee2 in Heartbeat::pulse (this=0x5615c5dff5a0 <(anonymous namespace)::global_objects()::storage+1504>, missed_pulses=0, label=std::unordered_map with 10 elements = {...})
    at /home/mud/mud/src/heartbeat.cpp:634
#15 0x00005615c5647954 in Heartbeat::operator() (this=0x5615c5dff5a0 <(anonymous namespace)::global_objects()::storage+1504>, missed_pulses=0) at /home/mud/mud/src/heartbeat.cpp:583
#16 0x00005615c549a327 in game_loop (epoll=10, mother_desc=8) at /home/mud/mud/src/comm.cpp:1494
#17 0x00005615c5499431 in stop_game (port=4000) at /home/mud/mud/src/comm.cpp:816
#18 0x00005615c5499142 in main_function (argc=3, argv=0x7ffce888c218) at /home/mud/mud/src/comm.cpp:757
#19 0x00005615c54986ad in main (argc=3, argv=0x7ffce888c218) at /home/mud/mud/src/main.cpp:4
(gdb)
```
