### ISSUE TITLE
Еще крешь

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1568]
```
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x00007ff9c195849e in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000557c74ac8984 in PrintProtectInfo (ch=0x557c8c4d5ef0, out=...) at /home/mud/mud/src/cmd/score.cpp:364
#3  0x0000557c74ace25b in PrintAdditionalInfo (ch=0x557c8c4d5ef0, out=...) at /home/mud/mud/src/cmd/score.cpp:638
#4  0x0000557c74ace51a in PrintScoreAll (ch=0x557c8c4d5ef0) at /home/mud/mud/src/cmd/score.cpp:671
#5  0x0000557c74ac640f in DoScore (ch=0x557c8c4d5ef0, argument=0x7fffc6a8a2e3 "все") at /home/mud/mud/src/cmd/score.cpp:89
#6  0x0000557c748a76e1 in command_interpreter (ch=0x557c8c4d5ef0, argument=0x7fffc6a8a2e0 "сч все") at /home/mud/mud/src/interpreter.cpp:1297
#7  0x0000557c7447e7b5 in process_io (epoll=10, mother_desc=8, events=0x557c8c34bb60) at /home/mud/mud/src/comm.cpp:1284
#8  0x0000557c74470a8d in game_loop (epoll=10, mother_desc=8) at /home/mud/mud/src/comm.cpp:1494
#9  0x0000557c7446fb81 in stop_game (port=4000) at /home/mud/mud/src/comm.cpp:818
#10 0x0000557c7446f892 in main_function (argc=3, argv=0x7fffc6a8ac98) at /home/mud/mud/src/comm.cpp:759
#11 0x0000557c7446edfd in main (argc=3, argv=0x7fffc6a8ac98) at /home/mud/mud/src/main.cpp:4
(gdb)
```

**Comment by bylins** [comment]
Jun  2 20:43:24 :: <Эстери, 512863> {97643} [кол !круг пуст! лж]
Jun  2 20:43:24 :: <Шабу, 512863> {97643} [кол !круг пуст! лж]
Jun  2 20:43:24 :: <Есгар, 512867> {63115} [сч все]
Jun  2 20:43:24 :: Crash detected !

**Comment by bylins** [comment]
голова сдвинута, вот сорцы на креш
git chekout ebcebdfe0a6a56fcf93a4a2ffb44adfa3cdd196b
