### ISSUE TITLE
Телега крешает мад

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1602]
```
==387786==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffffffb960 at pc 0x555557206b2f bp 0x7fffffffb410 sp 0x7fffffffaba0
WRITE of size 1060 at 0x7fffffffb960 thread T0
    #0 0x555557206b2e in __interceptor_vsprintf (/home/stribog/mud/build/circle+0x1cb2b2e)
    #1 0x555557206d5e in sprintf (/home/stribog/mud/build/circle+0x1cb2d5e)
    #2 0x555558541424 in TelegramBot::sendMessage(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/stribog/mud/src/cmd/telegram.cpp:76
    #3 0x555558540f29 in do_telegram(CharData*, char*, int, int) /home/stribog/mud/src/cmd/telegram.cpp:51
    #4 0x555557f73169 in command_interpreter(CharData*, char*) /home/stribog/mud/src/interpreter.cpp:1305
    #5 0x5555572c1110 in process_io(int, int, epoll_event*) (/home/stribog/mud/build/circle+0x1d6d110)
    #6 0x5555572a591b in game_loop(int, int) /home/stribog/mud/src/comm.cpp:1494
    #7 0x5555572a3c02 in stop_game(unsigned short) /home/stribog/mud/src/comm.cpp:818
    #8 0x5555572a361b in main_function(int, char**) /home/stribog/mud/src/comm.cpp:759
    #9 0x5555572a2231 in main /home/stribog/mud/src/main.cpp:4
    #10 0x7ffff75e7082 in __libc_start_main ../csu/libc-start.c:308
    #11 0x5555571cc5bd in _start (/home/stribog/mud/build/circle+0x1c785bd)

Address 0x7fffffffb960 is located in stack of thread T0 at offset 1056 in frame
    #0 0x5555585411c1 in TelegramBot::sendMessage(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/stribog/mud/src/cmd/telegram.cpp:65

  This frame has 1 object(s):
    [32, 1056) 'msgBuf' (line 68) <== Memory access at offset 1056 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/home/stribog/mud/build/circle+0x1cb2b2e) in __interceptor_vsprintf
Shadow bytes around the buggy address:
  0x10007fff76d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff76e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff76f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10007fff7720: 00 00 00 00 00 00 00 00 00 00 00 00[f3]f3 f3 f3
  0x10007fff7730: f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 00 00 00 00
  0x10007fff7740: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7750: 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
  0x10007fff7760: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7770: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==387786==ABORTING

```

**Comment by bylins** [comment]
Jun 24 16:39:43 :: player affect update: timer 0.031964, num players 1
Jun 24 16:39:45 :: player affect update: timer 0.032026, num players 1
Jun 24 16:39:47 :: player affect update: timer 0.031524, num players 1
Jun 24 16:39:48 :: интерпретер <коробейник, 5661> { 7196} []
Jun 24 16:39:49 :: player affect update: timer 0.031853, num players 1
Jun 24 16:39:51 :: <Индра, 5738> {  100} [телега стрибог [14:16] Жордий воззвал к богам : 'доброго времени суток! :) в связи с моим отсутствием в маде, прошу передать мое воеводство доброму
 молодцу Бромиру)]
Jun 24 16:39:51 :: интерпретер <Индра, 5738> {  100} [стрибог [14:16] Жордий воззвал к богам : 'доброго времени суток! :) в связи с моим отсутствием в маде, прошу передать мое воеводство до
брому молодцу Бромиру)]
Jun 24 16:39:51 :: Load ascii char стрибог
Jun 24 16:39:51 :: Load_char: Charmees loading
Jun 24 16:39:51 :: Load_char: Charmees: vnum: 4010
Jun 24 16:39:51 :: Load_char: Charmees: vnum: 4070
Jun 24 16:39:51 :: Load_char: Charmees: vnum: 60207
Jun 24 16:39:51 :: Load_char: Charmees: vnum: 66445
Jun 24 16:39:51 :: Load_char: Charmees: vnum: 66446
Jun 24 16:39:51 :: Load_char: Charmees: vnum: 98506
