### ISSUE TITLE
креши при проверки аффектов

### ISSUE THREAD

**Issue by bylins** [bylins/mud#2053]
![image](https://github.com/bylins/mud/assets/42086238/d1f920ba-dbd1-4a9c-8d53-3917d7e21c6f)
некорректно удаляются, переписать

**Comment by bylins** [comment]
void reset_affects(CharData *ch) {
тоже самое

**Comment by bylins** [comment]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000055be030b7223 in reset_affects (ch=ch@entry=0x55be133d7ff0) at /home/mud/mud/src/game_affects/affect_data.cpp:947
947                             || AFF_FLAGGED(ch, EAffect::kHelper))
(gdb) bt
#0  0x000055be030b7223 in reset_affects (ch=ch@entry=0x55be133d7ff0) at /home/mud/mud/src/game_affects/affect_data.cpp:947
#1  0x000055be03121a06 in raw_kill (ch=ch@entry=0x55be133d7ff0, killer=killer@entry=0x55be13aba650) at /home/mud/mud/src/game_fight/fight_stuff.cpp:669
#2  0x000055be0312277b in die (ch=ch@entry=0x55be133d7ff0, killer=killer@entry=0x55be13aba650) at /home/mud/mud/src/game_fight/fight_stuff.cpp:399
#3  0x000055be0310eabd in Damage::process_death (this=this@entry=0x7ffc728ccf40, ch=ch@entry=0x55be13aba650, victim=victim@entry=0x55be133d7ff0)
    at /home/mud/mud/src/game_fight/fight_hit.cpp:2213
#4  0x000055be0311b273 in Damage::Process (this=this@entry=0x7ffc728ccf40, ch=ch@entry=0x55be13aba650, victim=victim@entry=0x55be133d7ff0)
    at /home/mud/mud/src/game_fight/fight_hit.cpp:2678
#5  0x000055be031462be in CastDamage (level=<optimized out>, ch=ch@entry=0x55be13aba650, victim=victim@entry=0x55be133d7ff0,
    spell_id=spell_id@entry=ESpell::kFrostBreath) at /home/mud/mud/src/game_magic/magic.cpp:782
#6  0x000055be0311cbf3 in hit (ch=ch@entry=0x55be13aba650, victim=victim@entry=0x55be1c97f8b0, type=type@entry=ESkill::kUndefined,
    weapon=weapon@entry=fight::kMobAdd) at /home/mud/mud/src/game_fight/fight_hit.cpp:3669
#7  0x000055be0311d958 in exthit (ch=ch@entry=0x55be13aba650, victim=0x55be1c97f8b0, type=type@entry=ESkill::kUndefined, weapon=weapon@entry=fight::kMobAdd)
    at /home/mud/mud/src/game_fight/fight_hit.cpp:3947
#8  0x000055be0310b9ce in process_npc_attack (ch=ch@entry=0x55be13aba650) at /home/mud/mud/src/game_fight/fight.cpp:1845
#9  0x000055be0310c7f7 in perform_violence () at /home/mud/mud/src/game_fight/fight.cpp:2108
#10 0x000055be031fedf9 in std::__invoke_impl<void, void (*&)()> (__f=<optimized out>) at /usr/include/c++/11/bits/invoke.h:60
#11 std::__invoke_r<void, void (*&)()> (__fn=<optimized out>) at /usr/include/c++/11/bits/invoke.h:111
#12 std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/11/bits/std_function.h:290
#13 0x000055be031f32e5 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/11/bits/std_function.h:590
#14 (anonymous namespace)::SimpleCall::perform (this=<optimized out>) at /home/mud/mud/src/heartbeat.cpp:121
#15 0x000055be031f4e35 in Heartbeat::pulse (this=this@entry=0x55be0362c020 <(anonymous namespace)::global_objects()::storage+1632>,
    missed_pulses=missed_pulses@entry=0, label=std::unordered_map with 3 elements = {...}) at /home/mud/mud/src/heartbeat.cpp:650
#16 0x000055be031fea3b in Heartbeat::operator() (this=0x55be0362c020 <(anonymous namespace)::global_objects()::storage+1632>,
    missed_pulses=missed_pulses@entry=0) at /home/mud/mud/src/heartbeat.cpp:584
#17 0x000055be02fd8ee8 in game_loop (epoll=epoll@entry=10, mother_desc=mother_desc@entry=8) at /home/mud/mud/src/comm.cpp:1446
#18 0x000055be02fd904b in stop_game (port=port@entry=4000) at /home/mud/mud/src/comm.cpp:841
#19 0x000055be02fd98a4 in main_function (argc=2, argv=0x7ffc728cd9c8) at /home/mud/mud/src/comm.cpp:782
#20 0x000055be02fd08a6 in main (argc=<optimized out>, argv=<optimized out>) at /home/mud/mud/src/main.cpp:4

**Comment by bylins** [comment]
рип чармиса крешь, вечный цикл, вообще вопрос зачем при рипе снимать все аффекты? все равно чар будет спуржен,
ну тока если арена, но зачем снимать с чармисов обкаст?

**Comment by bylins** [comment]
готово
