### ISSUE TITLE
крешь в ассисте

### ISSUE THREAD

**Issue by bylins** [bylins/mud#2119]
Dec 26 14:51:07 :: <Новил, 850475> {80403} [приказ все помочь]
(gdb) bt
```
#0  0x0000000000000041 in ?? ()
#1  0x00005570e7ea132b in CharData::isAffected (this=this@entry=0x5570fa1bc640, flag=flag@entry=EAffect::kInvisible) at /home/mud/mud/src/entities/char_data.cpp:1750
#2  0x00005570e7ea154f in AFF_FLAGGED (flag=EAffect::kInvisible, ch=0x5570fa1bc640) at /home/mud/mud/src/entities/char_data.h:894
#3  INVIS_OK (obj=0x5570fa1bc640, sub=0x5571178f25e0) at /home/mud/mud/src/entities/char_data.h:911
#4  MORT_CAN_SEE (sub=sub@entry=0x5571178f25e0, obj=obj@entry=0x5570fa1bc640) at /home/mud/mud/src/entities/char_data.cpp:820
#5  0x00005570e7ea15e4 in IMM_CAN_SEE (sub=sub@entry=0x5571178f25e0, obj=obj@entry=0x5570fa1bc640) at /home/mud/mud/src/entities/char_data.cpp:900
#6  0x00005570e7ea1654 in CAN_SEE (sub=sub@entry=0x5571178f25e0, obj=obj@entry=0x5570fa1bc640) at /home/mud/mud/src/entities/char_data.cpp:908
#7  0x00005570e8262881 in do_assist (ch=0x5571178f25e0, argument=<optimized out>) at /home/mud/mud/src/game_fight/assist.cpp:59
#8  0x00005570e8094df1 in command_interpreter (ch=ch@entry=0x5571178f25e0, argument=<optimized out>, argument@entry=0x7ffe15ef5bd0 "помочь") at /home/mud/mud/src/interpreter.cpp:1300
#9  0x00005570e820719f in do_order (ch=0x55710432af70, argument=<optimized out>) at /home/mud/mud/src/cmd/order.cpp:84
#10 0x00005570e8094df1 in command_interpreter (ch=0x55710432af70, argument=<optimized out>, argument@entry=0x7ffe15ef6540 "приказ все помочь") at /home/mud/mud/src/interpreter.cpp:1300
#11 0x00005570e7e1d1cc in process_io (epoll=epoll@entry=10, mother_desc=mother_desc@entry=8, events=events@entry=0x5571007b9f30) at /home/mud/mud/src/comm.cpp:1232
#12 0x00005570e7e1aeca in game_loop (epoll=epoll@entry=10, mother_desc=mother_desc@entry=8) at /home/mud/mud/src/comm.cpp:1442
#13 0x00005570e7e1b03c in stop_game (port=port@entry=4000) at /home/mud/mud/src/comm.cpp:841
#14 0x00005570e7e1b895 in main_function (argc=2, argv=0x7ffe15ef7298) at /home/mud/mud/src/comm.cpp:782
#15 0x00005570e7e128a6 in main (argc=<optimized out>, argv=<optimized out>) at /home/mud/mud/src/main.cpp:4

```

**Comment by bylins** [comment]
Jan 20 21:37:05 :: <Новил, 757474> {80444} [приказ все помочь]
Jan 20 21:37:05 :: Crash detected !

и опять новил и в той же зоне, коры нету, профукал
