### ISSUE TITLE
креши 12.04.24

### ISSUE THREAD

**Issue by bylins** [bylins/mud#2182]
#0  0x00005614f8a7e4bf in GET_INVIS_LEV (ch=0x56150d428bb0) at /home/mud/mud/src/entities/char_data.h:872
872             if (ch->player_specials->saved.invis_level)
[Current thread is 1 (Thread 0x7fef1c600300 (LWP 304824))]
(gdb) bt
#0  0x00005614f8a7e4bf in GET_INVIS_LEV (ch=0x56150d428bb0) at /home/mud/mud/src/entities/char_data.h:872
#1  get_char_by_room (room=room@entry=0x5614fe74bed0, name=name@entry=0x7fffdbf48ca0 "\036\070\061\060\066\061\063") at /home/mud/mud/src/dg_script/dg_scripts.cpp:547
#2  0x00005614f8aa4956 in do_wsend (room=0x5614fe74bed0, argument=<optimized out>, subcmd=0) at /home/mud/mud/src/dg_script/dg_wldcmd.cpp:124
#3  0x00005614f8aa47a2 in wld_command_interpreter (room=room@entry=0x5614fe74bed0, argument=<optimized out>,
    argument@entry=0x7fffdbf49db0 "wsend \036\070\061\060\066\061\063 Осторожно отодвинув остатки сгнившего штакетника, вы увидели проход на юг.", trig=0x5614fe749f70)
    at /home/mud/mud/src/dg_script/dg_wldcmd.cpp:990
#4  0x00005614f8a97c85 in timed_script_driver (go=go@entry=0x5614fe74bed0, trig=<optimized out>, trig@entry=0x5614fe749f70, type=type@entry=2, mode=mode@entry=0)
    at /home/mud/mud/src/dg_script/dg_scripts.cpp:5587
#5  0x00005614f8a97f6b in script_driver (go=go@entry=0x5614fe74bed0, trig=trig@entry=0x5614fe749f70, type=type@entry=2, mode=mode@entry=0)
    at /home/mud/mud/src/dg_script/dg_scripts.cpp:5277
#6  0x00005614f8aa2a22 in command_wtrigger (actor=actor@entry=0x56151135d380, cmd=<optimized out>, argument=<optimized out>, argument@entry=0x561510689850 "штакетник")
    at /home/mud/mud/src/dg_script/dg_triggers.cpp:1325
#7  0x00005614f8c9a229 in command_interpreter (ch=0x56151135d380, argument=<optimized out>, argument@entry=0x7fffdbf4b050 "отодвинуть штакетник") at /home/mud/mud/src/interpreter.cpp:1218
#8  0x00005614f8a1b1a4 in process_io (epoll=epoll@entry=10, mother_desc=mother_desc@entry=8, events=events@entry=0x56150f64c8f0) at /home/mud/mud/src/comm.cpp:1232
#9  0x00005614f8a18ea3 in game_loop (epoll=epoll@entry=10, mother_desc=mother_desc@entry=8) at /home/mud/mud/src/comm.cpp:1442
#10 0x00005614f8a19015 in stop_game (port=port@entry=4000) at /home/mud/mud/src/comm.cpp:841
#11 0x00005614f8a1986d in main_function (argc=2, argv=0x7fffdbf4bda8) at /home/mud/mud/src/comm.cpp:782
#12 0x00005614f8a10886 in main (argc=<optimized out>, argv=<optimized out>) at /home/mud/mud/src/main.cpp:4

**Comment by bylins** [comment]
#0  timed_script_driver (go=go@entry=0x55e6b9447ef0, trig=trig@entry=0x55e6b9052dd0, type=type@entry=0, mode=mode@entry=1) at /home/mud/mud/src/dg_script/dg_scripts.h:309
#1  0x000055e69f362f6b in script_driver (go=0x55e6b9447ef0, trig=0x55e6b9052dd0, type=0, mode=mode@entry=1) at /home/mud/mud/src/dg_script/dg_scripts.cpp:5277
#2  0x000055e69f363016 in trig_wait_event (info=0x55e6b9333570) at /home/mud/mud/src/dg_script/dg_scripts.cpp:821
#3  0x000055e69f712f1a in process_events () at /home/mud/mud/src/dg_script/dg_event.cpp:87
#4  0x000055e69f511be1 in std::__invoke_impl<void, void (*&)()> (__f=<optimized out>) at /usr/include/c++/11/bits/invoke.h:60
#5  std::__invoke_r<void, void (*&)()> (__fn=<optimized out>) at /usr/include/c++/11/bits/invoke.h:111
#6  std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/11/bits/std_function.h:290
#7  0x000055e69f506319 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/11/bits/std_function.h:590
#8  (anonymous namespace)::SimpleCall::perform (this=<optimized out>) at /home/mud/mud/src/heartbeat.cpp:119
#9  0x000055e69f50821b in Heartbeat::pulse (this=this@entry=0x55e69f93e060 <(anonymous namespace)::global_objects()::storage+1632>, missed_pulses=missed_pulses@entry=0,
    label=std::unordered_map with 0 elements) at /home/mud/mud/src/heartbeat.cpp:648
#10 0x000055e69f511823 in Heartbeat::operator() (this=0x55e69f93e060 <(anonymous namespace)::global_objects()::storage+1632>, missed_pulses=missed_pulses@entry=0)
    at /home/mud/mud/src/heartbeat.cpp:582
#11 0x000055e69f2e3eb2 in game_loop (epoll=epoll@entry=10, mother_desc=mother_desc@entry=8) at /home/mud/mud/src/comm.cpp:1446
#12 0x000055e69f2e4015 in stop_game (port=port@entry=4000) at /home/mud/mud/src/comm.cpp:841
#13 0x000055e69f2e486d in main_function (argc=2, argv=0x7ffe538573f8) at /home/mud/mud/src/comm.cpp:782
#14 0x000055e69f2db886 in main (argc=<optimized out>, argv=<optimized out>) at /home/mud/mud/src/main.cpp:4

**Comment by bylins** [comment]
Apr 12 15:22:38 :: <Ломир, 4661> {85532} [потереть медальон]
Apr 12 15:22:38 :: SCRIPT LOG (Obj: 'медальон с изображением лошади', VNum: 2198, trig: 2103): oforce: no target found [строка: 22]
Apr 12 15:22:38 :: <Ломир, 4662> {85532} [вск]
Apr 12 15:22:38 :: <Ломир, 4663> {85532} [потереть медальон]
Apr 12 15:22:38 :: SCRIPT LOG (Obj: 'медальон с изображением лошади', VNum: 2198, trig: 2103): oforce: no target found [строка: 22]
Apr 12 15:22:38 :: <Ломир, 4664> {85532} [вск]
Apr 12 15:22:38 :: <Ломир, 4665> {85532} [потереть медальон]
Apr 12 15:22:38 :: SCRIPT LOG (Obj: 'медальон с изображением лошади', VNum: 2198, trig: 2103): oforce: no target found [строка: 22]
Apr 12 15:22:38 :: <Ломир, 4666> {85532} [вск]

**Comment by bylins** [comment]
#0  0x000055f8b49754bf in GET_INVIS_LEV (ch=0x55f8cea05fb0) at /home/mud/mud/src/entities/char_data.h:872
872             if (ch->player_specials->saved.invis_level)
[Current thread is 1 (Thread 0x7fb1528f4300 (LWP 306719))]
(gdb) bt
#0  0x000055f8b49754bf in GET_INVIS_LEV (ch=0x55f8cea05fb0) at /home/mud/mud/src/entities/char_data.h:872
#1  get_char_by_room (room=room@entry=0x55f8ba9abfd0, name=name@entry=0x7ffdd448fec0 "\036\070\061\060\066\061\063") at /home/mud/mud/src/dg_script/dg_scripts.cpp:547
#2  0x000055f8b499b956 in do_wsend (room=0x55f8ba9abfd0, argument=<optimized out>, subcmd=0) at /home/mud/mud/src/dg_script/dg_wldcmd.cpp:124
#3  0x000055f8b499b7a2 in wld_command_interpreter (room=room@entry=0x55f8ba9abfd0, argument=<optimized out>,
    argument@entry=0x7ffdd4490fd0 "wsend \036\070\061\060\066\061\063 Осторожно отодвинув остатки сгнившего штакетника, вы увидели проход на юг.", trig=0x55f8ba9aa070)
    at /home/mud/mud/src/dg_script/dg_wldcmd.cpp:990
#4  0x000055f8b498ec85 in timed_script_driver (go=go@entry=0x55f8ba9abfd0, trig=<optimized out>, trig@entry=0x55f8ba9aa070, type=type@entry=2, mode=mode@entry=0)
    at /home/mud/mud/src/dg_script/dg_scripts.cpp:5587
#5  0x000055f8b498ef6b in script_driver (go=go@entry=0x55f8ba9abfd0, trig=trig@entry=0x55f8ba9aa070, type=type@entry=2, mode=mode@entry=0)
    at /home/mud/mud/src/dg_script/dg_scripts.cpp:5277
#6  0x000055f8b4999a22 in command_wtrigger (actor=actor@entry=0x55f8cd357890, cmd=<optimized out>, argument=<optimized out>, argument@entry=0x55f8ce35f650 "штакетник")
    at /home/mud/mud/src/dg_script/dg_triggers.cpp:1324
#7  0x000055f8b4b91229 in command_interpreter (ch=0x55f8cd357890, argument=<optimized out>, argument@entry=0x7ffdd4492270 "отодвинуть штакетник") at /home/mud/mud/src/interpreter.cpp:1218
#8  0x000055f8b49121a4 in process_io (epoll=epoll@entry=10, mother_desc=mother_desc@entry=8, events=events@entry=0x55f8cb857ca0) at /home/mud/mud/src/comm.cpp:1232
#9  0x000055f8b490fea3 in game_loop (epoll=epoll@entry=10, mother_desc=mother_desc@entry=8) at /home/mud/mud/src/comm.cpp:1442
#10 0x000055f8b4910015 in stop_game (port=port@entry=4000) at /home/mud/mud/src/comm.cpp:841
#11 0x000055f8b491086d in main_function (argc=2, argv=0x7ffdd4492fc8) at /home/mud/mud/src/comm.cpp:782
#12 0x000055f8b4907886 in main (argc=<optimized out>, argv=<optimized out>) at /home/mud/mud/src/main.cpp:4
