### ISSUE TITLE
не работает oforce заколоть

### ISSUE THREAD

**Issue by bylins** [bylins/mud#462]
там проверки на непись и на то что есть оружие, имх дурная тема, уберу

**Comment by bylins** [comment]
```
==2383==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000001b8 (pc 0x558291d7f1d4 bp 0x7ffc28252710 sp 0x7ffc28252700 T0)
==2383==The signal is caused by a READ memory access.
==2383==Hint: address points to the zero page.
    #0 0x558291d7f1d3 in CObjectPrototype::get_val(unsigned long) const /home/mud/mud/lib/mirror/mud/src/obj.hpp:269
    #1 0x558292af184d in do_backstab(CHAR_DATA*, char*, int, int) /home/mud/mud/lib/mirror/mud/src/act.offensive.cpp:636
    #2 0x558292334c35 in command_interpreter(CHAR_DATA*, char*) /home/mud/mud/lib/mirror/mud/src/interpreter.cpp:1340
    #3 0x55829202b14a in do_wforce(ROOM_DATA*, char*, int, int) /home/mud/mud/lib/mirror/mud/src/dg_wldcmd.cpp:477
    #4 0x55829202fe8d in wld_command_interpreter(ROOM_DATA*, char*) /home/mud/mud/lib/mirror/mud/src/dg_wldcmd.cpp:1164
    #5 0x558291fd7a6d in timed_script_driver(void*, TRIG_DATA*, int, int) /home/mud/mud/lib/mirror/mud/src/dg_scripts.cpp:6084
    #6 0x558291fd4d80 in script_driver(void*, TRIG_DATA*, int, int) /home/mud/mud/lib/mirror/mud/src/dg_scripts.cpp:5666
    #7 0x558291fab52b in trig_wait_event(void*) /home/mud/mud/lib/mirror/mud/src/dg_scripts.cpp:927
    #8 0x558292d987d0 in process_events() /home/mud/mud/lib/mirror/mud/src/dg_event.cpp:100
    #9 0x5582921e50bf in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) /usr/include/c++/7/bits/std_function.h:316
    #10 0x5582921c45d5 in std::function<void ()>::operator()() const /usr/include/c++/7/bits/std_function.h:706
    #11 0x5582921a01ad in perform /home/mud/mud/lib/mirror/mud/src/heartbeat.cpp:140
    #12 0x5582921ac3aa in Heartbeat::pulse(int, std::__debug::unordered_map<unsigned long, double, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, double> > >&) /home/mud/mud/lib/mirror/mud/src/heartbeat.cpp:545
    #13 0x5582921ab5d7 in Heartbeat::operator()(int) /home/mud/mud/lib/mirror/mud/src/heartbeat.cpp:483
    #14 0x558291d66be7 in game_loop(int, int) /home/mud/mud/lib/mirror/mud/src/comm.cpp:1658
    #15 0x558291d64c4b in init_game(unsigned short) /home/mud/mud/lib/mirror/mud/src/comm.cpp:919
    #16 0x558291d6466e in main_function(int, char**) /home/mud/mud/lib/mirror/mud/src/comm.cpp:855
    #17 0x558291d62f8a in main /home/mud/mud/lib/mirror/mud/src/main.cpp:5
    #18 0x7f7a7a427b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #19 0x558291c64979 in _start (/home/mud/mud/lib/mirror/mud/bin/circle+0xe0a979)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mud/mud/lib/mirror/mud/src/obj.hpp:269 in CObjectPrototype::get_val(unsigned long) const
==2383==ABORTING

```
упало тут
![image](https://user-images.githubusercontent.com/42086238/58745972-6b653600-8461-11e9-8dc5-3e90930d0132.png)
почему на мобе  GET_OBJ_VAL(GET_EQ(ch, WEAR_WIELD), 3) асан положил мад?

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/58759962-b30bc080-853a-11e9-96b4-5bf5eb3cc344.png)
почему тогда тут не остановил асан?

**Comment by bylins** [comment]
строкой выше

**Comment by bylins** [comment]
я понял зачем такой костыль был сделан тут, чтоб наемы или чармисы не могли выполнять эти команды от приказа.
завтра поставлю проверку на них

**Comment by kvirund** [comment]
Потому что тут ешё нет разыменования NULL'а. Только проверка, NULL это или
нет.

With regards,
Anton Gorev


вс, 2 июн. 2019 г. в 05:31, bylins <notifications@github.com>:
