### ISSUE TITLE
непонятный крешь

### ISSUE THREAD

**Issue by bylins** [bylins/mud#477]
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./bin/circle 4000'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcpy_ssse3 () at ../sysdeps/x86_64/multiarch/strcpy-ssse3.S:43
[Current thread is 1 (Thread 0x7f46ab8bf300 (LWP 1853))]
#0  __strcpy_ssse3 () at ../sysdeps/x86_64/multiarch/strcpy-ssse3.S:43
#1  0x000055ed95bde195 in redit_save_to_disk (zone_num=265)
    at /home/mud/mud/src/redit.cpp:399
#2  0x000055ed95b8b0e0 in do_olc (ch=0x55edb3563660,
    argument=0x7ffe0a0deed3 " save 421", cmd=470, subcmd=0)
    at /home/mud/mud/src/olc.cpp:312
#3  0x000055ed95a5ddbe in command_interpreter (ch=0x55edb3563660,
    argument=0x7ffe0a0deed0 "red save 421")
    at /home/mud/mud/src/interpreter.cpp:1342
#4  0x000055ed9585bc82 in process_io (epoll=10, mother_desc=8,
    events=0x55ed97d37940) at /home/mud/mud/src/comm.cpp:1433
#5  0x000055ed9584e8bc in game_loop (epoll=10, mother_desc=8)
    at /home/mud/mud/src/comm.cpp:1654
#6  0x000055ed9584da5b in init_game (port=4000)
    at /home/mud/mud/src/comm.cpp:919
#7  0x000055ed9584d7a0 in main_function (argc=2, argv=0x7ffe0a0df478)
    at /home/mud/mud/src/comm.cpp:855
#8  0x000055ed9584cc1a in main (argc=2, argv=0x7ffe0a0df478)
    at /home/mud/mud/src/main.cpp:5
stribog@bylins:/home/mud/mud$

```

**Comment by bylins** [comment]
повторил
redit 4000
b
0
q
y
redit save 40
крешь

**Comment by ladon3434** [comment]
смотрю
