### ISSUE TITLE
еще креши

### ISSUE THREAD

**Issue by bylins** [bylins/mud#684]
#0  malloc_consolidate (av=av@entry=0x7f0733acdc40 <main_arena>) at malloc.c:4439
#1  0x00007f07337767d8 in _int_malloc (av=av@entry=0x7f0733acdc40 <main_arena>, bytes=bytes@entry=4096) at malloc.c:3703
#2  0x00007f07337792ed in __GI___libc_malloc (bytes=4096) at malloc.c:3065
#3  0x00007f073411c258 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x000055936174fd53 in vlog (format=0x559361b3591c "Crash detected !", args=0x7fff6aa63050, logfile=0x559363bb3980) at /home/mud/mud/src/logger.cpp:82
#5  0x0000559361750078 in log (format=0x559361b3591c "Crash detected !") at /home/mud/mud/src/logger.cpp:116
#6  0x00005593615258b9 in crash_handle () at /home/mud/mud/src/comm.cpp:3577
#7  <signal handler called>
#8  0x00007f073412ceda in std::__detail::_List_node_base::_M_unhook() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x0000559361793586 in std::__cxx11::list<std::shared_ptr<AFFECT_DATA<EApplyLocation> >, std::allocator<std::shared_ptr<AFFECT_DATA<EApplyLocation> > > >::_M_erase (this=0x559373e303b8, __position=
  std::shared_ptr<AFFECT_DATA<EApplyLocation>> (use count 1, weak count -1) = {get() = 0x55937c27c6d0}) at /usr/include/c++/7/bits/stl_list.h:1812
#10 0x0000559361792c9f in std::__cxx11::list<std::shared_ptr<AFFECT_DATA<EApplyLocation> >, std::allocator<std::shared_ptr<AFFECT_DATA<EApplyLocation> > > >::erase (this=0x559373e303b8, __position=
  std::shared_ptr<AFFECT_DATA<EApplyLocation>> (use count 1, weak count -1) = {get() = 0x55937c27c6d0}) at /usr/include/c++/7/bits/list.tcc:157
#11 0x0000559361ab90e2 in CHAR_DATA::affect_remove (this=0x559373e2faa0, affect_i=std::shared_ptr<AFFECT_DATA<EApplyLocation>> (use count 1, weak count -1) = {get() = 0x55937c27c6d0}) at /home/mud/mud/src/char.cpp:323
#12 0x000055936175880a in <lambda(const shared_ptr&)>::operator()(const CHAR_DATA::shared_ptr &) const (__closure=0x7fff6aa63910, i=std::shared_ptr<CHAR_DATA> (use count 3, weak count 0) = {...}) at /home/mud/mud/src/magic.cpp:927
#13 0x000055936176bab6 in std::_Function_handler<void(const std::shared_ptr<CHAR_DATA>&), player_affect_update()::<lambda(const shared_ptr&)> >::_M_invoke(const std::_Any_data &, const std::shared_ptr<CHAR_DATA> &) (__functor=...,
    __args#0=std::shared_ptr<CHAR_DATA> (use count 3, weak count 0) = {...}) at /usr/include/c++/7/bits/std_function.h:316
#14 0x000055936196d2f9 in std::function<void (std::shared_ptr<CHAR_DATA> const&)>::operator()(std::shared_ptr<CHAR_DATA> const&) const (this=0x7fff6aa63910, __args#0=std::shared_ptr<CHAR_DATA> (use count 3, weak count 0) = {...})
    at /usr/include/c++/7/bits/std_function.h:706
#15 0x000055936196c362 in std::for_each<std::_List_const_iterator<std::shared_ptr<CHAR_DATA> >, std::function<void (std::shared_ptr<CHAR_DATA> const&)> >(std::_List_const_iterator<std::shared_ptr<CHAR_DATA> >, std::_List_const_iterator<std::shared_ptr<CHAR_DATA> >, std::function<void (std::shared_ptr<CHAR_DATA> const&)>) (__first=std::shared_ptr<CHAR_DATA> (use count 3, weak count 0) = {get() = 0x559373e2faa0}, __last=
  std::shared_ptr<CHAR_DATA> (use count 1673154440, weak count 21906) = {get() = 0x5569}, __f=...) at /usr/include/c++/7/bits/stl_algo.h:3884
#16 0x000055936196b03c in Characters::foreach_on_copy(std::function<void (std::shared_ptr<CHAR_DATA> const&)>) const (this=0x5593620385a0 <(anonymous namespace)::global_objects()::storage+1152>, function=...)
    at /home/mud/mud/src/world.characters.cpp:95
#17 0x00005593617588ab in player_affect_update () at /home/mud/mud/src/magic.cpp:866
#18 0x00005593616b4adf in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#19 0x00005593616abcd8 in std::function<void ()>::operator()() const (this=0x559363ba4f88) at /usr/include/c++/7/bits/std_function.h:706
#20 0x0000559361699798 in (anonymous namespace)::SimpleCall::perform (this=0x559363ba4f80) at /home/mud/mud/src/heartbeat.cpp:140
#21 0x000055936169f290 in Heartbeat::pulse (this=0x559362038720 <(anonymous namespace)::global_objects()::storage+1536>, missed_pulses=9, label=std::unordered_map with 10 elements = {...}) at /home/mud/mud/src/heartbeat.cpp:545
#22 0x000055936169ed16 in Heartbeat::operator() (this=0x559362038720 <(anonymous namespace)::global_objects()::storage+1536>, missed_pulses=9) at /home/mud/mud/src/heartbeat.cpp:483
#23 0x000055936151fb79 in game_loop (epoll=10, mother_desc=8) at /home/mud/mud/src/comm.cpp:1631
#24 0x000055936151ecfb in stop_game (port=4000) at /home/mud/mud/src/comm.cpp:890
#25 0x000055936151ea40 in main_function (argc=3, argv=0x7fff6aa64048) at /home/mud/mud/src/comm.cpp:827
#26 0x000055936151deba in main (argc=3, argv=0x7fff6aa64048) at /home/mud/mud/src/main.cpp:5

**Comment by bylins** [comment]
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005586f21636eb in std::_List_iterator<std::shared_ptr<AFFECT_DATA<EApplyLocation> > >::operator++ (this=0x7ffdc5540248) at /usr/include/c++/7/bits/stl_list.h:162
162             _M_node = _M_node->_M_next;
[Current thread is 1 (Thread 0x7fdcf3841740 (LWP 5381))]
(gdb) bt
#0  0x00005586f21636eb in std::_List_iterator<std::shared_ptr<AFFECT_DATA<EApplyLocation> > >::operator++ (this=0x7ffdc5540248) at /usr/include/c++/7/bits/stl_list.h:162
#1  0x00005586f2280a5a in battle_affect_update (ch=0x55871505a750) at /home/mud/mud/src/magic.cpp:991
#2  0x00005586f2160a74 in update_round_affs () at /home/mud/mud/src/fight.cpp:1929
#3  0x00005586f2162221 in perform_violence () at /home/mud/mud/src/fight.cpp:2368
#4  0x00005586f21dcadf in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#5  0x00005586f21d3cd8 in std::function<void ()>::operator()() const (this=0x5586f3d7ed58) at /usr/include/c++/7/bits/std_function.h:706
#6  0x00005586f21c1798 in (anonymous namespace)::SimpleCall::perform (this=0x5586f3d7ed50) at /home/mud/mud/src/heartbeat.cpp:140
#7  0x00005586f21c7290 in Heartbeat::pulse (this=0x5586f2b60720 <(anonymous namespace)::global_objects()::storage+1536>, missed_pulses=0, label=std::unordered_map with 3 elements = {...}) at /home/mud/mud/src/heartbeat.cpp:545
#8  0x00005586f21c6d16 in Heartbeat::operator() (this=0x5586f2b60720 <(anonymous namespace)::global_objects()::storage+1536>, missed_pulses=0) at /home/mud/mud/src/heartbeat.cpp:483
#9  0x00005586f2047b79 in game_loop (epoll=10, mother_desc=8) at /home/mud/mud/src/comm.cpp:1631
#10 0x00005586f2046cfb in stop_game (port=4000) at /home/mud/mud/src/comm.cpp:890
#11 0x00005586f2046a40 in main_function (argc=3, argv=0x7ffdc55409c8) at /home/mud/mud/src/comm.cpp:827
#12 0x00005586f2045eba in main (argc=3, argv=0x7ffdc55409c8) at /home/mud/mud/src/main.cpp:5
