### ISSUE TITLE
show zones 104028

### ISSUE THREAD

**Issue by bylins** [bylins/mud#696]
остановка мада

**Comment by bylins** [comment]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6665801 in __GI_abort () at abort.c:79
#2  0x00007ffff7466781 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00005555564ab981 in std::__debug::vector<ZoneData, std::allocator<ZoneData> >::operator[] (this=0x555558d845e0 <(anonymous namespace)::global_objects()::storage+3232>, __n=532) at /usr/include/c++/7/debug/vector:417
#4  0x000055555728ca79 in do_show (ch=0x6210008f7100, argument=0x7fffffffda45 "zones 104028") at /home/stribog/mud/src/act.wizard.cpp:5212
#5  0x0000555556a61686 in command_interpreter (ch=0x6210008f7100, argument=0x7fffffffda40 "show zones 104028") at /home/stribog/mud/src/interpreter.cpp:1345
#6  0x00005555564a84b3 in process_io (epoll=11, mother_desc=9, events=0x627000292100) at /home/stribog/mud/src/comm.cpp:1406
#7  0x000055555648c3df in game_loop (epoll=11, mother_desc=9) at /home/stribog/mud/src/comm.cpp:1627
#8  0x000055555648a456 in stop_game (port=5555) at /home/stribog/mud/src/comm.cpp:890
#9  0x0000555556489e79 in main_function (argc=2, argv=0x7fffffffe578) at /home/stribog/mud/src/comm.cpp:827
#10 0x000055555648878d in main (argc=2, argv=0x7fffffffe578) at /home/stribog/mud/src/main.cpp:5
(gdb)
